### ISSUE TITLE
rog-fan-curve works not as expected

### ISSUE THREAD

**Issue by kersh1337228** [mechakotik/rog-daemon#3]
## Config:
- ASUS ROG Strix SCAR G732LWS (I7 10875H, RTX 2070 SUPER);
- System: Artix Linux dinit with 6.7.9.zen1-1 kernel;

## Issue description:
Executing `rog-fan-curve --fan=cpu --set=0c:0%,65c:0%,67c:0%,70c:10%,75c:10%,80c:15%,85c:15%,90c:20%` gives 
```
New custom fan curve was set successfully
```
But `rog-fan-curve --fan=cpu --get` gives 
```
Enabled
0c:0%,65c:0%,67c:0%,70c:9%,75c:9%,80c:14%,85c:14%,90c:20%
```
As you can definitely see those do not match and there is even more. When temperature is around 80c fans start speening on much higher velocities than 14% or even 20% using the config shown above. Of course, I use exactly the same fan-curve for my gpu.

**Comment by mechakotik** [comment]
These small mismatches happen because of rounding issues. BIOS stores fan percentage in range [0; 100], while Linux driver stores it in range [0; 255] for some reason. So when changing fan curves percentage gets converted to [0; 255] on the daemon side and then converted back to [0; 100] when driver does WMI call. I've fixed rounding, so percentage should be accurate now: fb8f12d.

Custom fan curves not working properly at around 80c is likely a BIOS thing to prevent overheating. Even if you set all zero fan curve, fans will start spinning at 80c anyway.

**Comment by kersh1337228** [comment]
Ok, I can confirm that this commit has fixed rounding issues , at least in my case. 

But what about BIOS. According to the fact you have created this indeed great tool, I can assume you have an ASUS ROG laptop too. In my case I don't care whether my CPU is 90c degrees or even 100c degrees (it is definitely a CPU overheating, my dGPU stays around under 80c degrees even under heavy loads, according to benchmarks I made) I don't want to hear this noise. Have you tried to patch BIOS somehow? I also know people say that undervolting helps to solve this issue too, have you tried it? I am sorry, if it is offtop, but I've mentioned it in issue description above so I think it is ok.

**Comment by mechakotik** [comment]
This never was a problem for me. Overheating leads to throttling in best case and permanent damage to hardware in worst case, so I'd better hear noise than let the CPU temp be >80c during everyday usage.

My current setup is `65c:0%,67c:40%`, and it remains silent almost all of the time. For heavy tasks such as games or multithreaded compiling I have another curve where fans are always 100%, so temps are around 70c even under full load.

**Comment by kersh1337228** [comment]
Ok, if the problem is in BIOS, then that is it. Thank you again.
